---
title: "互動式經濟資料視覺化"
output: output_format
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(ggplot2)
library(plotly)
library(sf)
# Paste your drake Rdata loading here

xfun::download_file("https://www.dropbox.com/s/zwlewu5enjlkrgy/maps_drake.Rdata?dl=1", mode="wb")
load("maps_drake.Rdata")
```
```{r}
xfun::download_file("https://www.dropbox.com/s/s4mv5ebhsqanpew/heritage.Rdata?dl=1", mode="wb")
load("heritage.Rdata")
```


```{r}
.root <- rprojroot::is_rstudio_project$make_fix_file()
drake$.updateCache()
drake$source_plan()
drake$makePlan()
heritageData <- jsonlite::fromJSON("https://data.boch.gov.tw/data/opendata/v2/assetsCase/1.1.json")
```

load target
```{r}
drake$loadTarget$pltWithoutI()
pltWithoutI
```

see original code
```{r}
drake$clipCommand$pltWithoutI() # store in your clipboard after running this command
```

paste in the place you want to see the code


#

```{r}
osmdata::getbb("Taiwan") -> bb_taiwan

osmdata::opq(bb_taiwan) %>%
  osmdata::add_osm_feature(key="admin_level", value="6") -> opq_twCounties6

osmdata::opq(bb_taiwan) %>%
  osmdata::add_osm_feature(key="admin_level", value="4") -> opq_twCounties4

list_sf_fun <- function(opq_twCounties6){
  osmdata::osmdata_sf(opq_twCounties6) -> list_sf_twCounties6
  osmdata::unname_osmdata_sf(list_sf_twCounties6) ->
    list_sf_twCounties_unnamed6
  
  return(list_sf_twCounties_unnamed6)
}

opq_twCounties6 %>%
  list_sf_fun() -> list_sf_twCounties_unnamed6

opq_twCounties4 %>%
  list_sf_fun() -> list_sf_twCounties_unnamed4

sf_counties4 <- list_sf_twCounties_unnamed4$osm_multipolygons
```

```{r}
library(sf)
sf_counties4$geometry
sf::st_crs(sf_counties4$geometry)
```

#Heritage

simple feature column

```{r}
drake$loadTarget$sf_unnamed_taipei()
drake$loadTarget$heritageData()
```

```{r}
drake$loadTarget$heritageData()
```

```{r}


heritageData %>% select(caseName, longitude, latitude) %>% 
  na.omit() -> heritageDataComplete

heritageData[1,][c("longitude","latitude")] %>% 
  as.matrix() %>%
  sf::st_point()

list_points <- vector("list", length(nrow(heritageDataComplete)))

for(i in 1:nrow(heritageDataComplete)){
  list_points[[i]] = {
    heritageDataComplete[i, ][c("longitude", "latitude")] %>%
      as.matrix() %>%
      sf::st_point()
  }
}

sfc_points <- sf::st_sfc(list_points)

```

```{r}
sf_heritage <- data.frame(
  caseName = heritageDataComplete$caseName,
  geometry = sfc_points
)

# convert proper data frame to sf data frame

sf_heritage <- sf::st_as_sf(sf_heritage)
```

```{r}
sf_taipei <- sf_unnamed_taipei$osm_multipolygons
```

```{r}
plot_ly() %>%
  add_sf(
    data = sf_taipei
  ) %>% 
  add_sf(
    data = sf_heritage
  )
```

#set CRS
```{r}
sf_taipei$geometry
# geographic CRS: WGS 84 (GIS)
# CRS 要一致才疊得上去

crsX <- sf::st_crs(sf_taipei$geometry)
sf::st_set_crs(sf_heritage, crsX) -> sf_heritage

sf_heritage
```
```{r}
plot_ly() %>%
  add_sf(
    data = sf_taipei
  ) %>% 
  add_sf(
    data = sf_heritage
  )
#範圍太大，所以要crop特定範圍
```
```{r}
sf::st_bbox(sf_taipei$geometry) -> bb_taipei
```

```{r}
sf::st_crop(sf_heritage, bb_taipei) -> sf_heritage
```
```{r}
plot_ly() %>%
  add_sf(
    data = sf_taipei
  ) %>% 
  add_sf(
    data = sf_heritage,
    color = I("lightblue"),
    stroke = I("black")
  )


```
rmapshaper::ms_simplify

```{r}

```

